### ISSUE TITLE
Produce an output for Visual Studio, so that the file is click-able and would go to the header file where the bus was inherited. Thanks! :) :) :)

### ISSUE THREAD

**Issue by SelfishOlex** [horvay/buslint#3]
Example of the buslint now:

1>buslint: buslint execution failed! Output:
1>Aw snap dawg!, you forgot to connect the bus PowerSourceSpawnerComponentBus::Handler in f:\work\UR3\dev\Gems\UR3_Towers\Code\Source\PowerSourceSpawnerComponent.cpp
1>
1>
1>
1>
1>Buslint took 0.0169999599457s to run.
1>GameStateComponent.cpp
1>

Example of VS error output that jumps to a file location:

1>f:\work\UR3\dev\Gems\UR3_Base\Code\Source\GameStateComponent.cpp(106): error C2065: 'ghkjhkj': undeclared identifier

**Comment by horvay** [comment]
This is a good idea.

FYI, putting lots of smiles doesn't make you a good person. It makes you a bad person. VERY BAD.

**Comment by SelfishOlex** [comment]
Oh, god, I'm sorry!

**Comment by horvay** [comment]
I deed it. It's closed. 💥
